# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:
    - jekyll-paginate
    - jekyll-gist
    - jekyll-sitemap

# Permalinks
permalink:        pretty
relative_permalinks: false

# site
#url:              http://localhost:4000
title:            rants and reviews
tagline:          'rants and reviews'
description:      "Online scratchpad for jotting down some ideas I've liked throughout the books I've read. And reviews, and other stuff as well"
baseurl:          https://vergiliu.github.io/
port:             4000
analytics:        UA-59542515-1

author:
  name:           Vergiliu
  url:            https://twitter.com/vergiliu

paginate:         20

# Custom vars
version:          0.5.1

github:
  repo:           https://github.com/vergiliu
